stages:
  build:
    nodeLabel: sbt
    steps:
      - sbt +universal:packageBin
    filesToStash:
      - serverless.yml
      - .nvmrc
      - target/universal/**
  deployDevInt:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless
        serverless deploy \
          --region us-west-2 \
          --stage devint
  deployUat:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless
        serverless deploy \
          --region us-west-2 \
          --stage uat
  deployProd:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless
        serverless deploy \
          --region us-west-2 \
          --stage prod
