stages:
  build:
    nodeLabel: sbt
    steps:
      - sbt test universal:packageBin
    filesToStash:
      - serverless.yml
      - .nvmrc
      - .env
      - target/universal/**
  deployDevInt:
    nodeLabel: nvm-deployer
    steps:
      - ./deploy.sh devint
  deployUat:
    nodeLabel: nvm-deployer
    steps:
      - ./deploy.sh uat
  deployProd:
    nodeLabel: nvm-deployer
    steps:
      - ./deploy.sh prod
